### PR TITLE
Ensure birthdate is not just a year for patients with estimated age.

### PR DESCRIPTION
**Pull request by slubwama**
https://app.asana.com/0/1133167201254913/1203004632145167

### CODE REVIEW

**Comment by ssmusoke** [comment]
@slubwama How can one view the payload for a profile without submitting it to the HIM?

**Comment by slubwama** [comment]
@ssmusoke you can find them in the sync_fhir_resource table

**Comment by slubwama** [comment]
> @slubwama How can one view the payload for a profile without submitting it to the HIM?

@ssmusoke you can find it in the sync_fhir_resource table

**Comment by ssmusoke** [comment]
@slubwama Thanks, another question, how can I trigger a profile generation without sending out data

**Pull request merged**
